#!/bin/bash

# Goal: send snapshots to other disks or remote hosts, to backup the snapshots.
# on local disks it only depends on btrfs tools, on remote systems it depends on
# ssh (and login using public/private keys), rsync and btrfs tools.

# in order to install this script in cron, please use lockFile (from daemontools
# package).

# Parse arguments
SRC=$1
DST=$2
TYPE=$3
HOST=$4

ssh='ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

# Check that DST is available, exit without errors if it is not.
if [ ! "$HOST" = "localhost" ]
	then # if it is up, check that the DST exists
		if ! $ssh -q "$HOST" exit;
			then # Assume host is down, or back disk not mounted.
				exit
		fi
	else # Local backup, could be to removable media, so check if it exists.
		if [ ! -e "$DST" ]
			then # Assume backup disk is not mounted.
				exit
		fi
fi

# for each source snapshot, ordered by age ASC.
for snap in $(find "$SRC"|sort |grep @"${TYPE}"\$); do
	echo "Backing up $snap"
	base=$(basename "$snap")

	# If snapshot already exists in DST then skip the backup, but save the name
	# so we might diff against it in upcoming snapshots.
	if [ ! "$HOST" = "localhost" ]
		then # For remote backups use ssh to see if the snapshot already exists.
			if $ssh "$HOST" stat "$DST"/"$base" \> /dev/null 2\>\&1
				then # file exists in backup already
					echo "File exists in backup, using for reference: $snap"
					prev=$snap # update prev, it may be used to diff.
					continue
			fi
		else # On local backups we can just check if the file exists.
			if [ -e "$DST"/"$base" ]
				then # The file exists in backup already
				echo "Snapshot $base already exists in dst $DST"
				prev=$snap # Update prev, it may be used to diff.
				continue
			fi
	fi

	# If this was the first (oldest) snapshot, then send the whole thing.
	# We test is if it was the oldest, by checkig if prev is empty:
	if [ -z "$prev" ]
		then # Prev was empty, so this is the first, so create a full backup.
			if [ ! "$HOST" = "localhost" ]
				then # Remote full backup, send everything over ssh directly.
					echo "Sending full snapshot $snap through ssh directly"
					btrfs send "$snap" | $ssh "$HOST" btrfs receive "$DST"
				else # Local full backup, pipe diff to DST fs.
					echo "Sending full snapshot $snap through pipe"
					btrfs send "$snap" | btrfs receive "$DST"
			fi
		else # Only send the diff between snap and prev, an incremental backup.
			if [ "$HOST" != "localhost" ]
				then # Remote incremental backup, rync the diff.
					backup="delta_$base"
					echo "Sending incremental from $prev to $snap using rsync"
					btrfs send -f /tmp/"$backup" -p "$SRC"/"$prev" "$SRC"/"$snap"
					echo "rsync -partial /tmp/$backup $HOST:/tmp/$backup"
					rsync -partial /tmp/"$backup" "$HOST":/tmp/"$backup"
					$ssh "$HOST" btrfs receive -f /tmp/"$backup" "$DST"
				else # Local incremental backup
					echo "Sending incremental from $prev to $snap through pipe"
					btrfs send -p "$SRC"/"$prev" "$SRC"/"$snap" | btrfs receive "$DST"
			fi
	fi
	# update prev, it may be used to diff.
	prev=$snap
done;
